### ISSUE TITLE
Add support for InitialWorkDirRequirement

### ISSUE THREAD

**Issue by KevinSayers** [nextflow-io/cwl2nxf#7]
In CWL InitialWorkDirRequirement can be used at the start of a commandline tool to specify files that must also be placed in tmp folder during processing. In nextflow this would involve just adding the additional files as inputs I believe.

**Comment by pditommaso** [comment]
Yes exactly, something like: 

```
process foo {
  input: 
   file 'x' from file('x')
   file 'y' from file('y')
}

**Comment by KevinSayers** [comment]
Yes it required a very minimal adjustment to get the CWL_RNAtoy converting and running correctly. I need to create a more complex test case. This will also require javascript as the InitialWorkDirRequirement can be an expression.

**Comment by KevinSayers** [comment]
The InitialWorkDirRequirement is currently supported. The expression portion will be fixed with continued work on JS handling.
